#!/bin/bash

# Check if we're running in minishift.
#
which minishift >> /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "$(minishift ip).nip.io"
  exit 0
fi

# Check if we're running in RHPDS.
#
apiserver=$(oc whoami --show-server)
if [[ $apiserver =~ ".example.opentlc.com" ]]; then
  echo $apiserver | sed -e 's|https://api\.\([^:]*\).*|apps.\1|'
  exit
fi


# Failsafe - assume we're running an all-in-one locally.
echo $(ip address show dev eth0 | grep "inet " | awk '{ print $2 }' | cut -d / -f 1).nip.io
